
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: https://reqres.in
        predicates:
          - Path=/users/{id}
        filters:
          - SetPath=/api/users/{id}